"""First Version

Revision ID: f134d8e20489
Revises: 
Create Date: 2022-04-29 18:49:12.216804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f134d8e20489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventors',
    sa.Column('key_id', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('location_city', sa.VARCHAR(), nullable=False),
    sa.Column('location_state', sa.VARCHAR(), nullable=False),
    sa.Column('location_longitude', sa.FLOAT(), nullable=True),
    sa.Column('location_latitude', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('patents',
    sa.Column('patent_id', sa.VARCHAR(), nullable=False),
    sa.Column('patent_title', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('patent_id')
    )
    op.create_table('inventor_patent_mapping',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('patent_id', sa.VARCHAR(), nullable=False),
    sa.Column('inventor_key_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['inventor_key_id'], ['inventors.key_id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.patent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventor_patent_mapping')
    op.drop_table('patents')
    op.drop_table('inventors')
    # ### end Alembic commands ###
